### ISSUE TITLE
gifs and videos wont load and crashes

### ISSUE THREAD

**Issue by fukiph** [CreativeMD/LittleFrames#23]
when im going to use the frames as large "tv" for cinema so i can watch basically anything within minecraft but when i inserted the link and save it, it didnt load and after a few second my game crashed. i tested the mod without any mods installed other than the mod itself same thing. idk whats wrong i installed vlc properly too

![image](https://user-images.githubusercontent.com/96836388/147683668-594f7ee3-bfbc-4a77-9eeb-2bf1abfebdcf.png)

**Comment by fukiph** [comment]
LF: 1.0.12
LT: 1.5.49
CC: 1.10.69

TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8681' Renderer: 'Intel(R) HD Graphics 630'
[00:22:83] [Client thread/INFO]: MinecraftForge v14.23.5.2860 Initialized
[00:22:87] [Client thread/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.
[00:22:08] [Client thread/INFO]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[00:22:15] [Client thread/INFO]: Replaced 1227 ore ingredients
[00:22:40] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraftforge.common.ForgeHooks ...
[00:22:53] [Client thread/INFO]: Searching C:\Users\Fuki\AppData\Roaming\.minecraft\versions\testing\mods for mods
[00:22:61] [Client thread/INFO]: Forge Mod Loader has identified 10 mods to load
[00:22:16] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, creativecoredummy, littletilescore, creativecore, littleframes, littletiles, tlauncher_custom_cape_skin] at CLIENT
[00:22:16] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, creativecoredummy, littletilescore, creativecore, littleframes, littletiles, tlauncher_custom_cape_skin] at SERVER
[00:22:22] [Thread-3/INFO]: Using sync timing. 200 frames of Display.update took 176286200 nanos
[00:22:26] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.network.PacketBuffer ...
[00:22:38] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CreativeCore, FMLFileResourcePack:LittleFrames, FMLFileResourcePack:LittleTiles, FMLFileResourcePack:TLSkinCape
[00:22:50] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.RenderGlobal ...
[00:22:62] [Client thread/INFO]: Processing ObjectHolder annotations
[00:22:66] [Client thread/INFO]: Found 1168 ObjectHolder annotations
[00:22:66] [Client thread/INFO]: Identifying ItemStackHolder annotations
[00:22:67] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[00:22:89] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[00:22:92] [Forge Version Check/INFO]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[00:22:95] [Client thread/INFO]: Applying holder lookups
[00:22:96] [Client thread/INFO]: Holder lookups applied
[00:23:01] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.BufferBuilder ...
[00:23:24] [Client thread/INFO]: Applying holder lookups
[00:23:24] [Client thread/INFO]: Holder lookups applied
[00:23:24] [Client thread/INFO]: Applying holder lookups
[00:23:24] [Client thread/INFO]: Holder lookups applied
[00:23:24] [Client thread/INFO]: Applying holder lookups
[00:23:25] [Client thread/INFO]: Holder lookups applied
[00:23:25] [Client thread/INFO]: Injecting itemstacks
[00:23:25] [Client thread/INFO]: Itemstack injection complete
[00:23:69] [Sound Library Loader/INFO]: Starting up SoundSystem...
[00:23:94] [Thread-5/INFO]: Initializing LWJGL OpenAL
[00:23:95] [Thread-5/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[00:23:41] [Thread-5/INFO]: OpenAL initialized.
[00:23:42] [Sound Library Loader/INFO]: Sound engine started
[00:23:19] [Client thread/INFO]: Max texture size: 8192
[00:23:05] [Client thread/INFO]: Created: 512x512 textures-atlas
[00:23:27] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.BlockModelRenderer ...
[00:23:35] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.vertex.VertexBuffer ...
[00:23:23] [Client thread/INFO]: Applying holder lookups
[00:23:23] [Client thread/INFO]: Holder lookups applied
[00:23:35] [Client thread/WARN]: Potentially Dangerous alternative prefix `minecraft` for name `littletilestileentity`, expected `littletiles`. This could be a intended override, but in most cases indicates a broken mod.
[00:23:35] [Client thread/WARN]: Potentially Dangerous alternative prefix `minecraft` for name `littletilestileentityticking`, expected `littletiles`. This could be a intended override, but in most cases indicates a broken mod.
[00:23:35] [Client thread/WARN]: Potentially Dangerous alternative prefix `minecraft` for name `littletilestileentityrendered`, expected `littletiles`. This could be a intended override, but in most cases indicates a broken mod.
[00:23:35] [Client thread/WARN]: Potentially Dangerous alternative prefix `minecraft` for name `littletilestileentitytickingrendered`, expected `littletiles`. This could be a intended override, but in most cases indicates a broken mod.
[00:23:70] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.chunk.RenderChunk ...
[00:23:70] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.chunk.RenderChunk ...
[00:23:06] [Client thread/INFO]: Injecting itemstacks
[00:23:06] [Client thread/INFO]: Itemstack injection complete
[00:23:64] [Client thread/INFO]: Forge Mod Loader has successfully loaded 10 mods
[00:23:95] [Client thread/INFO]: Narrator library for x64 successfully loaded
[00:23:49] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.network.NetHandlerPlayServer ...
[00:23:17] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[00:23:82] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[00:23:82] [Server thread/INFO]: Generating keypair
[00:23:94] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded workbench model
[00:23:95] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded importer model
[00:23:95] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded exporter model
[00:23:96] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded particle_emitter model
[00:23:96] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded blankomatic model
[00:23:96] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_cable1 model
[00:23:96] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_cable4 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_cable16 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_output1 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_output4 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_output16 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_input1 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_input4 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded single_input16 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded signal_display_16 model
[00:23:97] [Server thread/INFO]: [com.creativemd.littletiles.common.structure.type.premade.LittleStructurePremade:reloadPremadeStructures:85]: Loaded structure_builder model
[00:23:03] [Server thread/INFO]: Injecting existing registry data into this server instance
[00:23:26] [Server thread/INFO]: Applying holder lookups
[00:23:26] [Server thread/INFO]: Holder lookups applied
[00:23:36] [Server thread/INFO]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@48a2c191)
[00:23:91] [Server thread/INFO]: Loaded 488 advancements
[00:23:09] [Server thread/INFO]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@48a2c191)
[00:23:13] [Server thread/INFO]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@48a2c191)
[00:23:13] [Server thread/INFO]: Preparing start region for level 0
[00:23:88] [Server thread/INFO]: Unloading dimension -1
[00:23:90] [Server thread/INFO]: Unloading dimension 1
[00:23:92] [Server thread/INFO]: Changing view distance to 12, from 10
[00:23:60] [Netty Local Client IO #0/INFO]: Server protocol version 2
[00:23:60] [Netty Server IO #1/INFO]: Client protocol version 2
[00:23:60] [Netty Server IO #1/INFO]: Client attempting to join with 10 mods : minecraft@1.12.2,tlauncher_custom_cape_skin@1.4,littleframes@1.0.0,FML@8.0.99.99,forge@14.23.5.2860,littletilescore@1.0.0,mcp@9.42,creativecoredummy@1.0.0,creativecore@1.10.0,littletiles@1.5.0
[00:23:62] [Netty Local Client IO #0/INFO]: [Netty Local Client IO #0] Client side modded connection established
[00:23:64] [Server thread/INFO]: [Server thread] Server side modded connection established
[00:23:65] [Server thread/INFO]: fukiph[local:E:307238eb] logged in with entity id 7 at (-624.5, 4.0, -139.5)
[00:23:66] [Server thread/INFO]: fukiph joined the game
[00:23:72] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.chunk.ChunkRenderDispatcher ...
[00:23:04] [Server thread/INFO]: Saving and pausing game...
[00:23:07] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[00:23:11] [Client thread/INFO]: textures fukiph was added, skin: true,cape: false, max waiting: 17 ,during : 29712 
[00:23:39] [Server thread/INFO]: Saving and pausing game...
[00:23:44] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[00:24:54] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(SourceFile:47)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at team.creative.littleframes.common.packet.CreativeFramePacket.executeClient(CreativeFramePacket.java:49)
	at com.creativemd.creativecore.common.packet.PacketReciever$1.run(PacketReciever.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	... 9 more
	
	almost forgot

**Comment by CreativeMD** [comment]
Can you send me the entire latest.log file? There must be another issue before.

**Comment by fukiph** [comment]
[latest.log](https://github.com/CreativeMD/LittleFrames/files/7791543/latest.log)

**Comment by CreativeMD** [comment]
That is not the same log. I need the log of the crash. You could make this crash occur again and then send me the latest.log file.

**Comment by fukiph** [comment]
[latest.log](https://github.com/CreativeMD/LittleFrames/files/7802164/latest.log)

while trying to get the new latest.log the video somewhat work by playing the yt vid and play mc at the same time but i dont wanna play 2 same video due to memory usage

**Comment by CreativeMD** [comment]
Sorry, but I can't fix the issues with VLC. I hope things will be better when updating this mod to 1.18. I will switch to VLC 4 and hopefully that one works better. I will close this issue for now, I can't see any crashes/ issues in your log.
