### ISSUE TITLE
LittleFrames giving an error about StructureLocation

### ISSUE THREAD

**Issue by YouYouTheBoxx** [CreativeMD/LittleFrames#40]
//LittleFrames 1.19.2
//LittleTiles 1.19.2
//CreativeCore 1.19.2

Simple as that: [It only does this when combined with LittleTiles 1.19.2]

-- Head --
Thread: Render thread
Stacktrace:
	at team.creative.creativecore.common.network.type.NetworkFieldTypes.get(NetworkFieldTypes.java:108) ~[CreativeCore_FORGE_v2.9.3_mc1.19.2.jar%23216!/:2.9.3] {re:classloading}
-- MOD littleframes --
Details:
	Mod File: /C:/Users/youne/AppData/Local/.ftba/instances/f75f8384-97e8-4620-81c5-29da39e0f539/mods/LittleFrames_FORGE_v1.1.9_mc1.19.2.jar
	Failure message: LittleFrames (littleframes) encountered an error during the common_setup event phase
		java.lang.RuntimeException: No field type found for StructureLocation
	Mod Version: 1.1.9
	Mod Issue URL: https://github.com/CreativeMD/LittleFrames/issues
	Exception message: java.lang.RuntimeException: No field type found for StructureLocation
Stacktrace:
	at team.creative.creativecore.common.network.type.NetworkFieldTypes.get(NetworkFieldTypes.java:108) ~[CreativeCore_FORGE_v2.9.3_mc1.19.2.jar%23216!/:2.9.3] {re:classloading}
	at team.creative.creativecore.common.network.type.NetworkFieldTypes.get(NetworkFieldTypes.java:78) ~[CreativeCore_FORGE_v2.9.3_mc1.19.2.jar%23216!/:2.9.3] {re:classloading}
	at team.creative.creativecore.common.network.CreativeNetworkField.create(CreativeNetworkField.java:47) ~[CreativeCore_FORGE_v2.9.3_mc1.19.2.jar%23216!/:2.9.3] {re:classloading}
	at team.creative.creativecore.common.network.CreativeNetworkPacket.<init>(CreativeNetworkPacket.java:28) ~[CreativeCore_FORGE_v2.9.3_mc1.19.2.jar%23216!/:2.9.3] {re:classloading}
	at team.creative.creativecore.common.network.CreativeNetwork.registerType(CreativeNetwork.java:47) ~[CreativeCore_FORGE_v2.9.3_mc1.19.2.jar%23216!/:2.9.3] {re:classloading}
	at team.creative.littleframes.LittleFrames.init(LittleFrames.java:48) ~[LittleFrames_FORGE_v1.1.9_mc1.19.2.jar%23306!/:1.1.9] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.1.57.jar%23458!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.1.57.jar%23457!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by CreativeMD** [comment]
I think you need to update CreativeCore that should fix your issue.

**Comment by YouYouTheBoxx** [comment]
It's the latest one I got coming straight from your github source. So no, it doesn't fix my problem.

**Comment by CreativeMD** [comment]
Just don't use Littletiles yet ... sorry.
