### ISSUE TITLE
Any idea why it crashes?

### ISSUE THREAD

**Issue by SETHPROSYT** [CreativeMD/LittleFrames#63]
**I'm making a modpack and now out of nowhere the little picture frames crash, I don't know why**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.82_mc1.12.2.jar)
  MSICCoreMod (MyServerIsCompatible-1.12.2-1.0.jar)
  SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.8.jar)
  McLib core mod (mclib-2.4.2-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  Moving Elevators Plugin (movingelevators-1.4.4-forge-mc1.12.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_23.8.0_Forge_1.12.jar)
  LootrCore (lootr-1.12.2-0.6.2.jar)
  MixinBooter (!mixinbooter-8.6.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  SuperMartijn642's Core Lib Plugin (_supermartijn642corelib-1.1.15-forge-mc1.12.jar)
  infwithmend (infwithmend-forge-1.12.2-1.0.0.jar)
  Let Me Despawn (letmedespawn-1.12.2-forge-1.0.2.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.34.1_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/14/23 2:09 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleFrames (littleframes)
Caused by: java.lang.NoClassDefFoundError: Lme/srrapero720/watermedia/api/image/ImageCache;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.privateGetPublicFields(Unknown Source)
	at java.lang.Class.getFields(Unknown Source)
	at com.creativemd.littletiles.common.structure.registry.LittleStructureType.<init>(LittleStructureType.java:52)
	at com.creativemd.littletiles.common.structure.registry.LittleStructureRegistry.registerStructureType(LittleStructureRegistry.java:56)
	at team.creative.littleframes.LittleFrames.init(LittleFrames.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: me.srrapero720.watermedia.api.image.ImageCache
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 more
Caused by: java.lang.NullPointerException

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 809201392 bytes (771 MB) / 3758096384 bytes (3584 MB) up to 3758096384 bytes (3584 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3584m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 110 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by SrRapero720** [comment]
I have 2 teories.
1. You haven't installed [WATERMeDIA](https://www.curseforge.com/minecraft/mc-mods/watermedia)
2. You have a old version of [WATERMeDIA](https://www.curseforge.com/minecraft/mc-mods/watermedia/files/4782905) (probably 1.3.x)

**Comment by SETHPROSYT** [comment]
It worked but now I try to put gifs or videos they don't load or they lag
