### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by DN2048** [CreativeMD/LittleFrames#65]
Both LittleFrames and LittleTiles are giving the same error and crash on game start up.
Watermedia v2.0.8 and CreativeCore v2.11.2 are installed. I am missing another dependency? 

```
-- Head --
Thread: Render thread
Stacktrace:
	at team.creative.littleframes.LittleFrames.<clinit>(LittleFrames.java:33) ~[LittleFrames_FORGE_v1.3.2_mc1.20.1.jar%23176!/:1.3.2] {re:classloading}
-- MOD littleframes --
Details:
	Mod File: /E:/xxx/.minecraft/mods/LittleFrames_FORGE_v1.3.2_mc1.20.1.jar
	Failure message: LittleFrames (littleframes) has failed to load correctly
		java.lang.NoSuchMethodError: 'void team.creative.creativecore.common.network.CreativeNetwork.<init>(int, org.apache.logging.log4j.Logger, net.minecraft.resources.ResourceLocation)'
	Mod Version: 1.3.2
	Mod Issue URL: https://github.com/CreativeMD/LittleFrames/issues
	Exception message: java.lang.NoSuchMethodError: 'void team.creative.creativecore.common.network.CreativeNetwork.<init>(int, org.apache.logging.log4j.Logger, net.minecraft.resources.ResourceLocation)'
Stacktrace:
	at team.creative.littleframes.LittleFrames.<clinit>(LittleFrames.java:33) ~[LittleFrames_FORGE_v1.3.2_mc1.20.1.jar%23176!/:1.3.2] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23196!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23195!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- MOD littletiles --
Details:
	Mod File: /E:/xxx/.minecraft/mods/LittleTiles_ALPHA_v1.6.0-pre064_mc1.20.1.jar
	Failure message: LittleTiles (littletiles) has failed to load correctly
		java.lang.NoSuchMethodError: 'void team.creative.creativecore.common.network.CreativeNetwork.<init>(int, org.apache.logging.log4j.Logger, net.minecraft.resources.ResourceLocation)'
	Mod Version: 1.6.0-pre064
	Mod Issue URL: https://github.com/CreativeMD/LittleTiles/issues
	Exception message: java.lang.NoSuchMethodError: 'void team.creative.creativecore.common.network.CreativeNetwork.<init>(int, org.apache.logging.log4j.Logger, net.minecraft.resources.ResourceLocation)'
Stacktrace:
	at team.creative.littletiles.LittleTiles.<clinit>(LittleTiles.java:114) ~[LittleTiles_ALPHA_v1.6.0-pre064_mc1.20.1.jar%23177!/:1.6.0-pre064] {re:mixin,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23196!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23195!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 491074768 bytes (468 MiB) / 1073741824 bytes (1024 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.61
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 43363.65
	Virtual memory used (MB): 25458.95
	Swap memory total (MB): 10814.11
	Swap memory used (MB): 474.21
	JVM Flags: 21 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SmartBrainLib-neoforge-1.20.1-1.12.jar            |SmartBrainLib                 |smartbrainlib                 |1.12                |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
		LittleFrames_FORGE_v1.3.2_mc1.20.1.jar            |LittleFrames                  |littleframes                  |1.3.2               |ERROR     |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar   |EnchantmentDescriptions       |enchdesc                      |17.0.8              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |COMMON_SET|Manifest: NOSIGNATURE
		mcdoom-neoforge-1.20-6.0.6.jar                    |MCDoom                        |doom                          |6.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.20.1-10.0.0-169.jar        |Immersive Engineering         |immersiveengineering          |1.20.1-10.0.0-169   |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		customportalapi-0.0.1-forge-1.20.jar              |Custom Portal Api [Forge]     |customportalapi               |0.0.1-beta1-1.20    |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.598.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |COMMON_SET|Manifest: NOSIGNATURE
		NoChatReports-FORGE-1.20.1-v2.2.2.jar             |No Chat Reports               |nochatreports                 |1.20.1-v2.2.2       |COMMON_SET|Manifest: NOSIGNATURE
		watermedia-2.0.8.jar                              |WaterMedia                    |watermedia                    |2.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.2_mc1.20.1.jar           |CreativeCore                  |creativecore                  |2.11.2              |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |COMMON_SET|Manifest: NOSIGNATURE
		domum_ornamentum-1.20-1.0.138-BETA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.20-1.0.138-BETA   |COMMON_SET|Manifest: NOSIGNATURE
		Satako-7.0.14-1.20.1.jar                          |Satako                        |satako                        |7.0.14-1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		car-1.20.1-1.0.8.jar                              |Ultimate Car Mod              |car                           |1.20.1-1.0.8        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.3.5+1.20.1.jar                     |Curios API                    |curios                        |5.3.5+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		blockui-1.20.1-0.0.94-ALPHA.jar                   |UI Library Mod                |blockui                       |1.20.1-0.0.94-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.8.2_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.8.2              |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.34.1_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.34.1              |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |COMMON_SET|Manifest: NOSIGNATURE
		structurize-1.20.1-1.0.653-BETA.jar               |Structurize                   |structurize                   |1.20.1-1.0.653-BETA |COMMON_SET|Manifest: NOSIGNATURE
		multipiston-1.20-1.2.31-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.20-1.2.31-ALPHA   |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.0.5.jar                 |Bookshelf                     |bookshelf                     |20.0.5              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |COMMON_SET|Manifest: NOSIGNATURE
		minecolonies-1.20.1-1.1.240-RELEASE.jar           |MineColonies                  |minecolonies                  |1.20.1-1.1.240-RELEA|COMMON_SET|Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |COMMON_SET|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.8+1.20.1-universal.jar  |Minecraft Comes Alive         |mca                           |7.5.8+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		K-Turrets-3.0.10-1.20.1.jar                       |K-Turrets                     |k_turrets                     |3.0.10-1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		azurelib-forge-1.20.1-1.0.33.jar                  |AzureLib                      |azurelib                      |1.0.33              |COMMON_SET|Manifest: NOSIGNATURE
		player_companions_1.20.1-6.7.0.jar                |Player Companions             |player_companions             |6.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ServerTabInfo-1.20-1.3.8.jar                      |Server Tab Info               |servertabinfo                 |1.3.8               |COMMON_SET|Manifest: NOSIGNATURE
		LittleTiles_ALPHA_v1.6.0-pre064_mc1.20.1.jar      |LittleTiles                   |littletiles                   |1.6.0-pre064        |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: dc506e89-6375-4842-a805-71c7b4b3cd25
	FML: 47.2
	Forge: net.minecraftforge:47.2.0
```

**Comment by CreativeMD** [comment]
Update CreativeCore, this will fix your issue! Sorry for the trouble.
